fix getOffsetRect check if el is svg
VKCOM/vkjs pull request #148
Opened 2023-02-13 08:11 UTC by nmoiseev777

2023-02-13 08:31 UTC, SevereCloud requested changes

2023-02-13 08:31 UTC, SevereCloud commented on src/getOffsetRect.ts
>  export function getOffsetRect(el: HTMLElement | Text | null): Bounds {
```suggestion
export function getOffsetRect(el: HTMLElement | SVGElement | Text | null): Bounds {
```

2023-02-13 08:31 UTC, SevereCloud commented on src/getOffsetRect.ts
> +    height: box.height,
> **Note**
> `offsetWidth` / `offsetHeight` округляет значение до целого числа. Если вам нужно дробное значение, используйте [element.getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect).

Необходимо округлить значение

```suggestion
    width: Math.round(box.width),
    height: Math.round(box.height),
```

2023-06-14 09:34 UTC, fedorov-xyz approved these changes

2023-06-14 09:36 UTC, inomdzhon approved these changes

2023-06-14 09:40 UTC, merged