add isFunction, localStorage and formatTime functions
VKCOM/vkjs pull request #15
Opened 2020-11-03 18:32 UTC by lekzd

2020-11-03 19:11 UTC, fedorov-xyz commented on src/type_checkers.ts
> +  return obj && Object.prototype.toString.call(obj) === '[object Function]';
Чем такой способ лучше, чем `typeof value === 'function'`?

2020-11-03 19:11 UTC, fedorov-xyz commented on src/storage.ts
> +import { Dictionary } from 'types';
Мб `from './types'`?

2020-11-03 19:13 UTC, fedorov-xyz commented on src/date.ts
> +export function formatTime(timestamp: number, forceHours = false): string {
Уже есть функция `formatDuration` в `duration.ts`.

2020-11-03 20:23 UTC, NekR requested changes

2020-11-03 20:23 UTC, NekR commented on package.json
> +  "version": "0.8.1-beta.0",
В публичных через беты лучше не надо. Лучше сразу добавить билд шаг на МРы как в vkui. Кажется Игорь даже уже добавлял к этой репе.

Ну и была рекомендация импортить сразу .ts файлы у нас, а не скомпиленные. Так пробовали?

2020-11-03 20:23 UTC, NekR commented on src/index.ts
> +  vkLocalStorage,
В почему vkLocalStorage и вот это всё нужно в публичной репе?
Речь шла только о выносе определённых функция в публичный. То что внутреннее, то внутреннее.

2020-11-03 20:25 UTC, NekR commented on src/type_checkers.ts
> +  return obj && Object.prototype.toString.call(obj) === '[object Function]';
+

2020-11-04 09:31 UTC, lekzd commented on src/type_checkers.ts
> +  return obj && Object.prototype.toString.call(obj) === '[object Function]';
никакой очевидной разницы кроме того, что, просто копировал старое решение

2020-11-04 09:31 UTC, lekzd commented on src/storage.ts
> +import { Dictionary } from 'types';
да

2020-11-04 09:31 UTC, lekzd commented on src/date.ts
> +export function formatTime(timestamp: number, forceHours = false): string {
ок

2020-11-04 09:31 UTC, lekzd commented on package.json
> +  "version": "0.8.1-beta.0",
откатил версию

2020-11-04 09:32 UTC, lekzd commented on src/index.ts
> +  vkLocalStorage,
обсудили, переименовал

2020-11-04 09:42 UTC, fedorov-xyz commented on src/type_checkers.ts
> +export function isFunction(value: unknown): boolean {
Думаю, ещё лучше будет с type guard'ом:

```ts
export function isFunction(value: any): value is ((...args: any[]) => any) {
  return typeof value === 'function';
}
```

2020-11-05 06:36 UTC, lekzd commented on src/type_checkers.ts
> +export function isFunction(value: unknown): boolean {
интересное решение, ок

2020-11-05 07:44 UTC, fedorov-xyz approved these changes

2020-11-05 07:52 UTC, merged