fix(decodeHTMLEntities): add more entity
VKCOM/vkjs pull request #72
Opened 2022-10-15 11:23 UTC by SevereCloud

- Добавил все именные символы для HTML
- Исправил проблему с `;`

> Note. In SGML, it is possible to eliminate the final ";" after a character reference in some cases (e.g., at a line break or immediately before a tag). In other circumstances it may not be eliminated (e.g., in the middle of a word). We strongly suggest using the ";" in all cases to avoid problems with user agents that require this character to be present.

[5.3 Character references](https://www.w3.org/TR/1999/REC-html401-19991224/charset.html#entities)

Поэтому браузер превращает `&#34` в `"`

2022-12-13 11:59 UTC, GaijinBear commented on src/html/entity.ts
> +  'AElig;': '\u00C6',
Хардкод дубликатов можно убрать, добавив их программно

2022-12-13 12:02 UTC, NicoBurno commented on src/html/entity.ts
> +  'AElig;': '\u00C6',
Зачем нужны дубли с `;` и без `;`?

Если нужны - их можно добавить программно, а не хардкодом
Будет гораздо меньше весить

2022-12-13 12:11 UTC, NicoBurno commented on src/lib/replacer.ts
> +    if (typeof string !== 'string' || !string) {
Если на входе явно строка, то зачем проверять на то, что тут не строка?

2022-12-13 12:23 UTC, NicoBurno commented on src/html/entity.ts
> +  'AElig;': '\u00C6',
Если сначала сработает замена без `;`, то будет оставаться лишний `;`

2022-12-13 12:27 UTC, NicoBurno commented on src/html/entity.ts
> +  'AElig;': '\u00C6',
Стоит написать тест конкретно на этот кейс

2022-12-13 13:09 UTC, SevereCloud commented on src/html/entity.ts
> +  'AElig;': '\u00C6',
✅

До
![image](https://user-images.githubusercontent.com/14944123/207326468-5bea0a4d-d6c0-48ae-ae37-0bccd9568443.png)

После
<img width="415" alt="image" src="https://user-images.githubusercontent.com/14944123/207326426-87d6c62e-4e8a-4349-95bb-0ff8b8deed8a.png">

2022-12-13 13:09 UTC, SevereCloud commented on src/lib/replacer.ts
> +    if (typeof string !== 'string' || !string) {
убрал `typeof string !== 'string'`

2022-12-13 13:10 UTC, SevereCloud commented on src/html/entity.ts
> +  'AElig;': '\u00C6',
✅

Отсортировал ключи, тесты добавил на этот кейс

2022-12-13 14:32 UTC, NicoBurno approved these changes

2022-12-14 07:07 UTC, fedorov-xyz commented on src/html/__tests__/htmlEntities.test.js
> +    `&Pi Π`,
А почему тут первый кейс не декодировался?

2022-12-14 09:51 UTC, SevereCloud commented on src/html/__tests__/htmlEntities.test.js
> +    `&Pi Π`,
Эта сущность декодируется [только](https://html.spec.whatwg.org/multipage/named-characters.html) с `;` на конце

<img width="464" alt="image" src="https://user-images.githubusercontent.com/14944123/207563096-e0d1dded-4c87-41f4-b61b-24839996740c.png">

```
data:text/html, &Pi &Pi;
```

2022-12-14 10:29 UTC, NicoBurno requested changes

2022-12-14 10:29 UTC, NicoBurno commented on src/html/entity.ts
> +export function buildFullNamedEntities() {
Выглядит как усложнение, так как теперь есть необходимость вызывать этот метод для мутации fullNamedEntities, что неочевидно.
Вычисления не настолько тяжелые, чтобы выносить их со стадии инициализации модуля.

Можно было бы сделать просто с самовызывающейся функцией:
```
export const fullNamedEntities = (() => {
  // Все тоже самое
})();
```

2022-12-14 10:29 UTC, NicoBurno commented on src/html/entity.ts
> +  Object.keys(namedEntitiesWithoutSemicolon).map((entitie) => {
map создаст лишний массив в памяти, замени на forEach
На следующей строчке тоже

2022-12-14 10:29 UTC, NicoBurno commented on src/html/entity.ts
> +  Object.keys(namedEntitiesWithoutSemicolon).map((entitie) => {
entity вместо entitie

2022-12-14 10:29 UTC, NicoBurno commented on src/html/entity.ts
> +  if (Object.keys(fullNamedEntities).length > 0) {
Каждый раз при вызове функции будет создаваться мусор в виде массива из ключей
Это будет ощутимо бить по производительности, в случаях вызова в цикле

Если все таки решишь не делать самовызывающейся функцией, то хотябы замени на флаг:
```
let initialized = false;

export function buildFullNamedEntities() {
  if (initialized) {
    return;
  }

  // some code

  initialized = true;
}
```

При самовызывающейся функции в этом не будет необходимости

2022-12-14 11:24 UTC, SevereCloud commented on src/html/entity.ts
> +  Object.keys(namedEntitiesWithoutSemicolon).map((entitie) => {
✅

2022-12-14 11:24 UTC, SevereCloud commented on src/html/entity.ts
> +  Object.keys(namedEntitiesWithoutSemicolon).map((entitie) => {
✅

2022-12-14 11:25 UTC, SevereCloud commented on src/html/entity.ts
> +  if (Object.keys(fullNamedEntities).length > 0) {
✅ Добавли флаг

2022-12-14 12:03 UTC, NicoBurno commented on src/html/entity.ts
> +export function buildFullNamedEntities() {
Можно расставить `/*#__PURE__*/`
И будет нормально шейкаться

2022-12-14 12:04 UTC, NicoBurno approved these changes

2022-12-14 12:27 UTC, NicoBurno commented on src/html/entity.ts
> +export function buildFullNamedEntities() {
Накидал пруф того, что с комментом будет все ок:
https://github.com/NicoBurno/tree-shake-test

2022-12-16 10:28 UTC, fedorov-xyz approved these changes

2022-12-16 10:34 UTC, merged